targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: fr
          input_directory: assets/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/i18n/generated
          output_file_name: translations.g.dart
          format:
            enabled: true
            width: 80